# Generated by Django 4.1.7 on 2023-03-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoCRUD123', '0003_student_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='city',
        ),
        migrations.RemoveField(
            model_name='student',
            name='country',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default='computerscience', max_length=50),
        ),
    ]
