# Generated by Django 4.1.7 on 2023-03-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoCRUD123', '0004_remove_student_city_remove_student_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(default='', max_length=50),
        ),
    ]
